sudo: false
language: csharp
solution: CsharpUtilities.net40.sln
 
install:
  - nuget restore ./CsharpUtilities/CsharpUtilities.net40.sln
  - nuget install xunit.runners -Version 1.9.2 -OutputDirectory testrunner
 
script:
  - xbuild /p:Configuration=Release ./CsharpUtilities/CsharpUtilities.net40.sln
