sudo: false
language: csharp
solution: CsharpUtilities.net40.sln
 
install:
  - nuget restore ./CsharpUtilities/CsharpUtilities.net40.sln
  - nuget restore ./CsharpUtilities/CsharpUtilities.net45.sln
  - nuget install xunit.runners -Version 1.9.2 -OutputDirectory testrunner
 
script:
  - xbuild /p:Configuration=Release ./CsharpUtilities/CsharpUtilities.net40.sln
  - xbuild /p:Configuration=Release ./CsharpUtilities/CsharpUtilities.net45.sln
  - mono ./testrunner/xunit.runners.1.9.2/tools/xunit.console.clr4.exe ./CsharpUtilities/CsharpUtilities.Tests/bin/Release/net40/CsharpUtilities.Tests.dll
  - mono ./testrunner/xunit.runners.1.9.2/tools/xunit.console.clr4.exe ./CsharpUtilities/CsharpUtilities.Tests/bin/Release/net45/CsharpUtilities.Tests.dll
